### ISSUE TITLE
memory access error

### ISSUE THREAD

**Issue by jembrown** [TreeScaper/TreeScaper#2]
Need to fix bug related to illegal memory access when conducting certain types of NLDR in the command-line version.

**Comment by jembrown** [comment]
@zhifeng1703 Is this bug also fixed? Based on our calls, I think it might be, but want to be sure before closing.

**Comment by zhifeng1703** [comment]
This bug is trigger when classic scaling method (MDS) is called for non-Euclidean distance matrix. This method it only meant to be performing NLDR on Euclidean distance matrix, for other type of distance matrices, it may fail with the presence of negative eigenvalues. 

Yet MDS is also served as a "lousy" way to get initial guess for other methods, performing on general distance matrix. In this case, negative eigenvalues and associated eigenvectors, if they exist, are dropped. The particular bug addressed in this thread happened in this dropping process and it is fixed now. Therefore this issue is closed now.
